language: python

python:
  - "3.7"
  - "3.6"

install:
  - pip install pytest
  - pip install pytest-cov
  - pip install tox-travis
  - pip install coveralls

script:
  - tox
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then pytest --cov=src/plugable; fi

after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" = "3.7" ]; then coveralls; fi
