name: plugable
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip to latest
        run: python3 -m pip install --upgrade pip
      - name: Run test cases & lint checks
        run: make test
      - name: Convert coverage data into LCOV format 
        run: poetry run coverage lcov
      - name: Send code coverage results to Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
          parallel: true
  sync-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Let Coveralls know that all tests have finished
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
  publish-pkg:
    runs-on: ubuntu-latest
    needs: run-tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build packages
        run: make build
      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true