name: Plugable CI/CD Pipeline
on: 
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
env:
  BUILD_PYTHON_VERSION: "3.10"
jobs:
  check:
    name: Check if testing is required
    outputs:
      test: ${{ steps.test.outputs.any_changed }}
      build: ${{ steps.build.outputs.any_changed }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if test-impacting files modified
        id: test
        uses: tj-actions/changed-files@v29.0.2
        with:
          files: |
            src
            test
            poetry.lock
            .github
      - name: Check if build-impacting files modified
        id: build
        uses: tj-actions/changed-files@v29.0.2
        with:
          files: |
            src
            .github

  test:
    name: "Run unit, formatting, and linting tests"
    needs: check
    if: needs.check.outputs.test == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip to latest
        run: python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: Setup pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ matrix.python-version }} }}
      - name: Setup Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ matrix.python-version }} }}
      - name: Setup package cache
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Run test cases & lint checks
        run: make test
      - name: Convert coverage data into LCOV format 
        run: poetry run coverage lcov
      - name: Send code coverage results to Coveralls
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
          parallel: true

  coverage:
    name: "Finalise parallel coverage upload"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Let Coveralls know that all tests have finished
        uses: coverallsapp/github-action@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true

  build:
    name: "Build packages"
    runs-on: ubuntu-latest
    needs: 
      - check
      - test
    if: needs.check.outputs.build == 'true'
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}
      - name: Upgrade pip to latest
        run: python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: Setup pip cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ env.BUILD_PYTHON_VERSION }} }}
      - name: Setup Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ runner.os }}-${{ env.BUILD_PYTHON_VERSION }} }}
      - name: Setup package cache
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-${{ runner.os }}-${{ env.BUILD_PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install Poetry
        run: make install
      - name: Determine package version
        id: version
        run: "echo ::set-output name=version::$(poetry run python3 ./scripts/determine_version.py $(git describe --tags --candidates=99 --exclude \"*-*\"))"
      - name: Save version to file
        run: echo "${{ steps.version.outputs.version }}" > VERSION
      - name: Set version
        run: poetry version ${{ steps.version.outputs.version }}
      - name: Build packages
        run: make build
      - name: Upload package artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-pkgs
          path: dist/
      - name: Upload license
        uses: actions/upload-artifact@v3
        with:
          name: license-file
          path: LICENSE

  prerelease:
    name: "Release new candidate version"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Download license file
        uses: actions/download-artifact@v3
        with:
          name: license-file
      - name: Download built packages
        uses: actions/download-artifact@v3
        with:
          name: dist-pkgs
      - name: List out directory
        run: ls -lah ./
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ needs.build.outputs.version }}"
          prerelease: true
          title: "Prerelease Build: ${{ needs.build.outputs.version }}"
          files: |
            LICENSE
            plugable-*

  release:
    name: "Release new version"
    runs-on: "ubuntu-latest"
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: build
    steps:
      - name: Download license file
        uses: actions/download-artifact@v3
        with:
          name: license-file
      - name: Download built packages
        uses: actions/download-artifact@v3
        with:
          name: dist-pkgs
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ needs.build.outputs.version }}"
          prerelease: false
          title: "Release Build: ${{ needs.build.outputs.version }}"
          files: |
            LICENSE
            plugable-*

  publish:
    name: "Publish new release to PyPI"
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Download built packages
        uses: actions/download-artifact@v3
        with:
          name: dist-pkgs
      - name: Make dist directory
        run: mkdir ./dist
      - name: Move packages into dist directory
        run: mv ./plugable-* ./dist
      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.5
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
